INSERT INTO livros_biblia (nome, quantidade_capitulos, numero_versiculos, testamento, temas_principais, createdAt, updatedAt) VALUES 
('Gênesis', 50, 1533, 'Velho', 'Criação, Queda, Promessa de Redenção', NOW(), NOW()), 
('Êxodo', 40, 1213, 'Velho', 'Libertação, Aliança, Lei', NOW(), NOW()), 
('Levítico', 27, 859, 'Velho', 'Leis Cerimoniais, Sacrifícios, Pureza', NOW(), NOW()), 
('Números', 36, 1288, 'Velho', 'Censo, Peregrinação, Promessas', NOW(), NOW()), 
('Deuteronômio', 34, 959, 'Velho', 'Relembre, Lei, Aliança', NOW(), NOW()), 
('Josué', 24, 658, 'Velho', 'Conquista, Terra Prometida, Liderança', NOW(), NOW()), 
('Juízes', 21, 618, 'Velho', 'Ciclo de Pecado, Libertação, Juízes', NOW(), NOW()), 
('Rute', 4, 85, 'Velho', 'Fidelidade, Redenção, Família', NOW(), NOW()), 
('1 Samuel', 31, 810, 'Velho', 'Monarquia, Saul, Davi', NOW(), NOW()), 
('2 Samuel', 24, 695, 'Velho', 'Reinado de Davi, Pecado, Arrependimento', NOW(), NOW()), 
('1 Reis', 22, 816, 'Velho', 'Divisão do Reino, Salomão, Profetas', NOW(), NOW()), 
('2 Reis', 25, 719, 'Velho', 'Cair do Reino, Profecias, Exílio', NOW(), NOW()), 
('1 Crônicas', 29, 942, 'Velho', 'Genealogias, Reinado de Davi, Adoração', NOW(), NOW()), 
('2 Crônicas', 36, 822, 'Velho', 'História do Reino, Templos, Reforma', NOW(), NOW()), 
('Esdras', 10, 280, 'Velho', 'Retorno do Exílio, Reconstrução, Lei', NOW(), NOW()), 
('Neemias', 13, 406, 'Velho', 'Reforma, Liderança, Jerusalém', NOW(), NOW()), 
('Ester', 10, 167, 'Velho', 'Providência, Coragem, Identidade', NOW(), NOW()), 
('Jó', 42, 1070, 'Velho', 'Sofrimento, Justiça, Fé', NOW(), NOW()), 
('Salmos', 150, 2461, 'Velho', 'Adoração, Louvor, Lamento', NOW(), NOW()), 
('Provérbios', 31, 915, 'Velho', 'Sabedoria, Moral, Instrução', NOW(), NOW()), 
('Eclesiastes', 12, 222, 'Velho', 'Vaidade, Propósito, Sabedoria', NOW(), NOW()), 
('Cânticos', 8, 117, 'Velho', 'Amor, Relação, Intimidade', NOW(), NOW()), 
('Isaías', 66, 1292, 'Velho', 'Profecias, Esperança, Redenção', NOW(), NOW()), 
('Jeremias', 52, 1364, 'Velho', 'Profecia, Lamentação, Juízo', NOW(), NOW()), 
('Lamentações', 5, 154, 'Velho', 'Lamento, Destruição, Esperança', NOW(), NOW()), 
('Ezequiel', 48, 1273, 'Velho', 'Visões, Restauração, Profecia', NOW(), NOW()), 
('Daniel', 12, 357, 'Velho', 'Profecia, Sonhos, Fidelidade', NOW(), NOW()), 
('Oséias', 14, 197, 'Velho', 'Fidelidade, Amor, Redenção', NOW(), NOW()), 
('Joel', 3, 73, 'Velho', 'Juízo, Esperança, Restauração', NOW(), NOW()), 
('Amós', 9, 146, 'Velho', 'Justiça, Juízo, Riqueza', NOW(), NOW()), 
('Obadias', 1, 21, 'Velho', 'Orgulho, Juízo, Redenção', NOW(), NOW()), 
('Jonas', 4, 48, 'Velho', 'Missão, Arrependimento, Misericórdia', NOW(), NOW()), 
('Miquéias', 7, 105, 'Velho', 'Justiça, Esperança, Profecia', NOW(), NOW()), 
('Naum', 3, 47, 'Velho', 'Juízo, Nínive, Profecia', NOW(), NOW()), 
('Habacuque', 3, 56, 'Velho', 'Injustiça, Fé, Esperança', NOW(), NOW()), 
('Sofonias', 3, 53, 'Velho', 'Juízo, Restauração, Esperança', NOW(), NOW()), 
('Ageu', 2, 38, 'Velho', 'Reforma, Templo, Dedicação', NOW(), NOW()), 
('Zacarias', 14, 211, 'Velho', 'Profecias, Restauração, Messias', NOW(), NOW()), 
('Malaquias', 4, 55, 'Velho', 'Profecia, Aliança, Esperança', NOW(), NOW()), 
('Mateus', 28, 1071, 'Novo', 'Vida de Jesus, Discípulos, Reino de Deus', NOW(), NOW()), 
('Marcos', 16, 678, 'Novo', 'Ministério de Jesus, Ação, Testemunho', NOW(), NOW()), 
('Lucas', 24, 1151, 'Novo', 'Vida de Jesus, Compaixão, Salvação', NOW(), NOW()), 
('João', 21, 879, 'Novo', 'Vida de Jesus, Divindade, Amor', NOW(), NOW()), 
('Atos', 28, 1007, 'Novo', 'Crescimento da Igreja, Espírito Santo, Missão', NOW(), NOW()), 
('Romanos', 16, 433, 'Novo', 'Justificação, Fé, Graça', NOW(), NOW()), 
('1 Coríntios', 16, 437, 'Novo', 'Igreja, Unidade, Amor', NOW(), NOW()), 
('2 Coríntios', 13, 257, 'Novo', 'Consolo, Ministério, Generosidade', NOW(), NOW()), 
('Gálatas', 6, 149, 'Novo', 'Liberdade, Lei, Espírito', NOW(), NOW()), 
('Efésios', 6, 155, 'Novo', 'Igreja, Unidade, Crescimento Espiritual', NOW(), NOW()), 
('Filipenses', 4, 104, 'Novo', 'Alegria, Unidade, Humildade', NOW(), NOW()), 
('Colossenses', 4, 95, 'Novo', 'Cristo, Plenitude, Instrução', NOW(), NOW()), 
('1 Tessalonicenses', 5, 89, 'Novo', 'Esperança, Retorno de Cristo, Exortação', NOW(), NOW()), 
('2 Tessalonicenses', 3, 47, 'Novo', 'Retorno de Cristo, Trabalho, Falsas Ensinos', NOW(), NOW()), 
('1 Timóteo', 6, 113, 'Novo', 'Liderança, Igreja, Ensino', NOW(), NOW()), 
('2 Timóteo', 4, 83, 'Novo', 'Fidelidade, Ministério, Exortação', NOW(), NOW()), 
('Tito', 3, 46, 'Novo', 'Boas Obras, Liderança, Ensinamento', NOW(), NOW()), 
('Filémon', 1, 25, 'Novo', 'Perdão, Relações, Escravo', NOW(), NOW()), 
('Hebreus', 13, 303, 'Novo', 'Cristo, Sacerdócio, Fé', NOW(), NOW()), 
('Tiago', 5, 108, 'Novo', 'Fé, Obras, Sabedoria', NOW(), NOW()), 
('1 Pedro', 5, 105, 'Novo', 'Sofrimento, Esperança, Santidade', NOW(), NOW()), 
('2 Pedro', 3, 61, 'Novo', 'Falsos Mestres, Promessa, Paciente', NOW(), NOW()), 
('1 João', 5, 105, 'Novo', 'Amor, Fé, Vida Eterna', NOW(), NOW()), 
('2 João', 1, 13, 'Novo', 'Verdade, Amor, Falsos Mestres', NOW(), NOW()), 
('3 João', 1, 15, 'Novo', 'Hospitalidade, Líderes, Comunidade', NOW(), NOW()), 
('Judas', 1, 25, 'Novo', 'Falsos Mestres, Advertência, Fidelidade', NOW(), NOW()), 
('Apocalipse', 22, 404, 'Novo', 'Profecia, Esperança, Fim dos Tempos', NOW(), NOW());
